version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: myapps-joplin_app_1
      APP_PORT: 22300

  db:
    image: postgres:16-alpine@sha256:REMPLACER_PAR_VOTRE_SHA256_POSTGRES
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      POSTGRES_USER: joplin
      POSTGRES_DB: joplin
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      default:
        aliases:
          - joplin-db

  app:
    image: joplin/server:latest@sha256:REMPLACER_PAR_VOTRE_SHA256_JOPLIN
    restart: on-failure
    depends_on:
      - db
    environment:
      APP_PORT: 22300
      APP_BASE_URL: ${APP_JOPLIN_BASE_URL:-http://umbrel.local:22300}
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: joplin-db
    volumes:
      - ${APP_DATA_DIR}/data/joplin:/data
    networks:
      default:
        aliases:
          - joplin-server